export const allTotalDivReq = () => {
  const totalReqs = {
    oper: {
      RSU: {
        Class_I: 0,
        Class_II: 0,
        Class_III: 0,
        Class_IV: 0,
        Class_V: 0,
        Class_VI: 0,
        Recall_completed_case: 0,
        Recall_any: 0,
        Exam_Class_II: 0,
        Exam_Class_V: 0,
        Polishing: 0,
        Sealant: 0,
        PRR: 0,
        Caries_control: 0,
        Emergency_tx: 0,
        Inlay: 0,
        Onlay: 0,
        Diastema_closure: 0,
        Veneer: 0,
        Minimum_total_R: 0,
      },
      CDA: {
        Class_I: 0,
        Class_II: 0,
        Class_III_or_IV: 0,
        Class_V: 0,
        Any_class: 0,
      },
    },
    endo: {
      RSU: {
        RCT_Anterior_or_Premolar: 0,
        RCT_Molar: 0,
        Emergency_RCT: 0,
        Talk_case: 0,
        Recall_6_months: 0,
        Exam_RCT: 0,
      },
      CDA: {
        RCT_Anterior_or_Premolar: 0,
        Exam_RCT: 0,
      },
    },
    perio: {
      RSU: {
        Case_G: 0,
        Case_P: 0,
        Complexities: 0,
        OHI_1st_Exam: 0,
        OHI_2n_Exam: 0,
        SRP_1st_Exam: 0,
      },
      CDA: {
        //Case_G: 0,
        Case_P: 0,
        CDA_Cases: 0,
        SRP_2nd_Exam: 0,
      },
    },
    prosth: {
      RSU: {
        CD_Upper: 0,
        CD_Lower: 0,
        MRPD: 0,
        ARPD: 0,
        Crown: 0,
        Post_Core_Crown: 0,
        Bridge_3_units: 0,
        Exam_design_RPD: 0,
        Exam_crown_preparation: 0,
      },
      CDA: {
        CD_Upper: 0,
        CD_Lower: 0,
        MRPD: 0,
        ARPD: 0,
        Crown: 0,
        Post_Core_Crown: 0,
        Bridge_3_units: 0,
      },
    },
    diag: {
      RSU: {
        Complete_case_examination: 0,
        Assistant: 0,
        CPC_or_Journal_club: 0,
        Complete_splint: 0,
        Recall_cases_splint: 0,
      },
      CDA: {
        Complete_case_examination: 0,
        Chief_complaint_examination: 0,
        Biopsy_Blood_chemistry_or_soft_tissue_lesion_interpretation: 0,
        TMDs_case_examination: 0,
      },
    },
    radio: {
      RSU: {
        Full_mouth_periapical_radiograph: 0,
        Periapical_radiograph: 0,
        Bitewing_radiograph: 0,
        Extraoral_and_Special_technique_radiograph: 0,
        Film_interpretation: 0,
        Journal_club: 0,
      },
      CDA: {
        Exam_periapical_radiograph_anterior_teeth: 0,
        Exam_periapical_radiograph_posterior_teeth: 0,
        Exam_bitewing_radiograph: 0,
      },
    },
    sur: {
      RSU: {
        Aseptic_station: 0,
        Suture_station: 0,
        Vital_sign_station: 0,
        IANB_exam: 0,
        Impact_in_model: 0,
        Extraction: 0,
        Impact: 0,
        Exam_extraction_RSU: 0,
        Exam_impact_RSU: 0,
      },
      CDA: {
        Extraction: 0,
        Impact: 0,
        Exam_extraction_CDA: 0,
        Exam_impact_CDA: 0,
      },
    },
    ortho: {
      RSU: {
        Charting: 0,
        Photograph_taking: 0,
        Impression_taking_Upper: 0,
        Impression_taking_Lower: 0,
        Removable_appliance: 0,
        Inserting_removable_appliance: 0,
        Assisting_adjust_fixed_appliance: 0,
        Plaster_Pouring: 0,
        Model_Trimming: 0,
        Case_analysis: 0,
      },
      CDA: {
        Inserting_removable_appliance: 0,
        Case_analysis: 0,
      },
    },
    pedo: {
      RSU: {
        Comprehensive_examination_and_treatment_plan_in_new_patient: 0,
        Comprehensive_examination_and_treatment_plan_in_recall_patient: 0,
        Photographs_and_Radiographs: 0,
        Caries_risk_assessment_and_Management: 0,
        Sealant: 0,
        Filling_or_PRR: 0,
        Primary_molar_class_II_restoration: 0,
        Stainless_steel_crown_in_posterior_teeth: 0,
        Pulpectomy_Step_OC_and_LT_or_Pulpotomy: 0,
        Pulpectomy_Step_MI_and_FRC: 0,
        Extraction: 0,
        Miscellaneous_work: 0,
        Exam_Inferior_alveolar_nerve_block_injection: 0,
        Exam_Rubber_dam_application: 0,
      },
      CDA: {
        Comprehensive_examination_and_treatment_plan: 0,
        Caries_risk_assessment_and_Management: 0,
        Sealant: 0,
        Filling_or_PRR: 0,
        Pulpectomy_or_Pulpotomy: 0,
        Stainless_steel_crown: 0,
        Extraction: 0,
      },
    },
  };
  return totalReqs;
};
